services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: easy2meet-web
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    environment:
      - TZ=Europe/Warsaw
      - NODE_OPTIONS=--dns-result-order=ipv4first
    dns:
      - 1.1.1.1
      - 8.8.8.8
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev
    stdin_open: true
    tty: true